- name: Get EC2 Public IP
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Gather EC2 Facts
      ec2_instance_facts:
        region: us-west-2
        filters:
          "tag:Name": "{{name_tag}}"
      register: ec2_facts
    - name: Out Put IP
      debug:
        var: ec2_facts.instances[0].public_ip_address
 