- name: Create Nagios Host Group
  hosts: all
  tasks:
  - name: Deploy Nagios Host Group Template
    template:
      src: files/sd-host_group.temp
      dest: /usr/local/nagios/etc/servers/hostgroups/sd-{{lab_code}}.cfg
  - name: Update LABCODE
    replace:
      path: /usr/local/nagios/etc/servers/hostgroups/sd-{{lab_code}}.cfg
      regexp: "CHANGE"
      replace: "{{lab_code}}"
  - name: Restart Nagios
    service:
      name: nagios
      state: restarted