- name: Site Depot-CMS-LB-Initial Config 
  hosts: all
  tasks:
- name: Rename CMS LB Server
  import_playbook: linux-rename_server.yaml
- name: Trigger ServiceNow Discovery
  import_playbook: servicenow-trigger_discovery.yaml
  vars:
    host_ip: "{{ansible_default_ipv4.address}}"
- name: Add Server to Zabbix
  import_playbook: zabbix_deploy_agent_config.yaml