- name: Site Depot-CMS-TRAP-Initial Config 
  hosts: all
  gather_facts: true
  tasks:
- name: Rename Windows Server
  import_playbook: windows-rename_server.yaml
- name: Run ServiceNow Discovery
  import_playbook: servicenow-trigger_discovery_windows.yaml
- name: Trigger ServiceNow Orchestration
  hosts: all
  gather_facts: true
  tasks:
    - name: Trigger ITOMMIDDeploy
      win_uri:
        url: https://{{discovery_instance}}.service-now.com/api/snc/restfulworkflow/ITOMMIDDeploy?u_mid_ip={{ansible_ip_addresses[0]}}&u_mid_type={{server_role}}
        method: POST
        user: websrvc
        password: Aw3s0m34321
        force_basic_auth: yes