- name: Add WWW Host to Zabbix
  hosts: "{{tower_ip}}"
  gather_facts: false
  become: no
  tasks:
  - name: Create a new host or update an existing host's info
    local_action:
      module: zabbix_host
      server_url: http://{{zabbix_ip}}/zabbix/
      login_user: "{{zabbix_user}}"
      login_password: "{{zabbix_pass}}"
      host_name: "{{host_name}}"
      visible_name: "{{host_name}}"
      host_groups:
        - DB-Marketing
      link_templates:
        - Template App HTTP Service
        - Template App SSH Service
        - Template ICMP Ping
        - Template OS Linux
      status: enabled
      state: present
      inventory_mode: automatic
      interfaces:
        - type: 1
          main: 1
          useip: 1
          ip: "{{host_ip}}"
          dns: ""
          port: 10050
