- name: Change EC2 Instance State
  hosts: localhost
  gather_facts: false
  vars:
    region: "{{region}}"
  tasks:
    - name: Change State
      ec2:
        instance_ids: "{{itemid}}"
        region: "{{region}}"
        state: "{{state}}"
        wait: True
 