- name: Provision EC2 Instance from AMI
  hosts: localhost
  gather_facts: false
  vars:
    region: us-west-2
  tasks:
    - name: Deploy Instance
      ec2:
        region: "{{region}}"
        key_name: "{{key}}"
        instance_type: "{{hw_type}}"
        image: "{{ami}}"
        vpc_subnet_id: "{{subnet}}"
        assign_public_ip: yes
        wait: yes
