- name: Update Youtube Video on Wordpress
  hosts: "{{host}}"
  tasks:
  - name: Push Template SQL Script
    template:
      src: files/site_config-pipe-acndev01.tmp
      dest: /root/youtube.sql
  - name: Update URL in SQL Script
    replace:
      path: /root/youtube.sql
      regexp: "YOUTUBE"
      replace: "{{url}}"
  - name: Update Site Name in SQL Script
    replace:
      path: /root/youtube.sql
      regexp: "SITENAME"
      replace: "{{sitename}}"
  - name: Update URL in SQL Script
    replace:
      path: /root/youtube.sql
      regexp: "SITEDES"
      replace: "{{sitedes}}"
  - name: Import youtube.sql into DB
    mysql_db:
      login_user: "{{user}}"
      login_password: "{{password}}"
      login_host: localhost
      state: import
      name: "{{db}}"
      target: /root/youtube.sql
