- name: Add MYSQL Host to Zabbix
  hosts: "{{tower_ip}}"
  gather_facts: false
  become: no
  tasks:
  - name: Create a new host or update an existing host's info
    local_action:
      module: zabbix_host
      server_url: http://{{zabbix_ip}}/zabbix/
      login_user: "{{zabbix_user}}"
      login_password: "{{zabbix_pass}}"
      host_name: "{{host_name}}"
      visible_name: "{{host_name}}"
      host_groups:
        - Site Depot CMS - {{lab_code}}
        - Linux servers
      link_templates:
        - MySQL by Zabbix agent 2
#        - MySQL by ODBC
        - SSH Service
        - ICMP Ping
        - Linux by Zabbix agent
      status: enabled
      state: present
      inventory_mode: manual
      interfaces:
        - type: 1
          main: 1
          useip: 1
          ip: "{{host_ip}}"
          dns: ""
          port: "10050"
